CREATE TABLE `pristroy_products` (
 `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
 `item_id` int(11) unsigned NOT NULL,
 `item_tao_id` varchar(30) NOT NULL,
 `title` varchar(255) NOT NULL DEFAULT '',
 `description` text NOT NULL,
 `images` varchar(1024) DEFAULT '',
 `price` float unsigned NOT NULL DEFAULT '0',
 `currency` VARCHAR(255) NOT NULL DEFAULT 'RUB',
 `quantity` tinyint(2) unsigned NOT NULL DEFAULT '1',
 `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
 `updated_at` datetime DEFAULT NULL,
 `status` tinyint(1) unsigned NOT NULL DEFAULT '0',
 `user_id` int(11) unsigned NOT NULL,
 `user_login` varchar(100) NOT NULL,
 `config_id` varchar(20) NOT NULL,
 `config_text` varchar(100) NOT NULL,
 `fullinfo` text NOT NULL,
 `reject_reason` varchar(255) NOT NULL DEFAULT '',
 PRIMARY KEY (`id`),
 KEY `idx_item_id` (`item_id`),
 KEY `idx_user_id` (`user_id`),
 KEY `idx_user_login` (`user_login`),
 KEY `idx_status` (`status`),
 KEY `idx_created` (`created_at`),
 KEY `idx_updated` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;